[package]
name = "tsunami"
version = "0.1.0"
edition = "2021"

[dependencies]
raw-socket  = { path = "../raw-socket" }
anyhow = "1.0.75"
pnet = "0.34.0"
rand = "0.8.5"
structopt = "0.3.26"
tokio = { version = "1.34.0", features = ["full"] }
