name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.builder }}
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-musl
            builder: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            builder: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            builder: ubuntu-latest
          - target: x86_64-unknown-freebsd
            builder: ubuntu-latest
          - target: x86_64-apple-darwin
            builder: macos-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --target ${{ matrix.target }}
        if: matrix.target == 'x86_64-unknown-linux-gnu'
